"""Unit tests for the menu models."""

from decimal import Decimal

from django.test import TestCase

from menu.models import Category, MenuItem, Order, OrderItem


class CategoryModelTests(TestCase):
    def test_slug_is_autogenerated_from_name(self):
        category = Category.objects.create(name="Main Courses")
        self.assertEqual(category.slug, "main-courses")

    def test_explicit_slug_is_preserved(self):
        category = Category.objects.create(name="Desserts", slug="sweets")
        self.assertEqual(category.slug, "sweets")

    def test_default_ordering_by_display_order(self):
        a = Category.objects.create(name="A", display_order=2)
        b = Category.objects.create(name="B", display_order=1)
        self.assertEqual(list(Category.objects.all()), [b, a])


class MenuItemModelTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Starters")

    def test_slug_is_autogenerated(self):
        item = MenuItem.objects.create(
            category=self.category, name="Garlic Bread", price=Decimal("5.00")
        )
        self.assertEqual(item.slug, "garlic-bread")

    def test_duplicate_names_get_unique_slugs(self):
        first = MenuItem.objects.create(
            category=self.category, name="Soup", price=Decimal("6.00")
        )
        second = MenuItem.objects.create(
            category=self.category, name="Soup", price=Decimal("6.50")
        )
        self.assertEqual(first.slug, "soup")
        self.assertEqual(second.slug, "soup-2")
        self.assertNotEqual(first.slug, second.slug)


class OrderModelTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name="Mains")
        self.item_a = MenuItem.objects.create(
            category=self.category, name="Steak", price=Decimal("30.00")
        )
        self.item_b = MenuItem.objects.create(
            category=self.category, name="Fish", price=Decimal("20.00")
        )

    def test_order_item_subtotal(self):
        order = Order.objects.create(
            customer_name="Test", customer_email="t@example.com"
        )
        line = OrderItem.objects.create(
            order=order, menu_item=self.item_a, quantity=3, unit_price=Decimal("30.00")
        )
        self.assertEqual(line.subtotal, Decimal("90.00"))

    def test_recalculate_total_sums_line_items(self):
        order = Order.objects.create(
            customer_name="Test", customer_email="t@example.com"
        )
        OrderItem.objects.create(
            order=order, menu_item=self.item_a, quantity=2, unit_price=Decimal("30.00")
        )
        OrderItem.objects.create(
            order=order, menu_item=self.item_b, quantity=1, unit_price=Decimal("20.00")
        )
        self.assertEqual(order.recalculate_total(), Decimal("80.00"))
        order.refresh_from_db()
        self.assertEqual(order.total_amount, Decimal("80.00"))
