# Generated by Django 5.1.4 on 2026-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(help_text='Delivery address.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=30),
        ),
    ]
