# Generated by Django 5.1.4 on 2026-07-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_latitude_order_longitude_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menuitem'),
        ),
    ]
