# Generated by Django 5.1.4 on 2026-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_backfill_orderitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
