# Generated by Django 5.1.4 on 2026-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Active Order',
                'verbose_name_plural': 'Active Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
