# Generated by Django 5.1.4 on 2026-07-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_activeorder_deliveredorder_order_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Order',
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.order',),
        ),
    ]
